### ISSUE TITLE
Can Identify method be modified to return full results from Open Subtitles?

### ISSUE THREAD

**Issue by sarathkcm** [vankasteelj/opensubtitles-api#11]
Currently Identify returns only limited fields from the Open Subtitles response, can it be modified to return all the fields returned from OS, like awards, goofs, rating votes, languages etc?

**Comment by sarathkcm** [comment]
Suggestions for implementation approach
1. Keep an unwanted fields list and copy all the fields except these from the OS response

``` javascript
        var unwantedFields = ["imdb_status", "plot", "from_redis", "request_from", "id", "kind"];
        _.extend(data.metadata,response.data);
        _(unwantedFields).each(function(field){_.unset(data.metadata,field)});

       // do all the processing like 
       // data.metadata.synopsis = response.data.plot && response.data.plot.match(/add a plot/i) !== null ? undefined : response.data.plot;
```

OR
2. In the options object send the list of fields the calling method expects from the result object, and copy only those fields in the identify.js

``` javascript
OpenSubtitles.identify({
    path: "<path>", 
    extend:true,
    extend_fields:["aka","awards","votes","goofs","etc","etc"]
}).then(function(result){
    console.log(result);  
});
```

I need all the fields returned by the OS API, and I wanted to use the 'opensubtitles-api' as is, without making any local changes to it. Request you to please implement the feature. Or if you could tell me which approach, I can make the changes and raise a pull request. 

Regards,
Sarath

**Comment by vankasteelj** [comment]
Hi, you can use:

```
var data;
OpenSubtitles.identify({
    path: 'foo/bar',
    extend: false
}).then(function (res) {
    data = res;
    return OpenSubtitles.api.GetIMDBMovieDetails(OpenSubtitles.credentials.status.token, res.metadata.imdbid.replace('tt',''));
}).then(function (res) {
    data.metadata = res.data;
    return data;
})
```

I must have had a perfectly good reason for writing it that way, maybe the other results aren't consistent across requests? Or maybe it's because `kind` is terribly written? If it were just about renaming 'plot' to 'synopsis', I wouldn't have gone that far. I don't recall and I'll have to check.

**Comment by sarathkcm** [comment]
May be because the response has totally unwanted fields like I mentioned in the code above?

**Comment by sarathkcm** [comment]
Thanks for the reply, I like the identify method you wrote, which pretty much does every check by itself and that's what I liked most about your api client. I know I can chain the method with other api calls to achieve what I want, but I would like to keep that logic in the library itself rather than writing in the main code. If you could make it happen that would be nice :) . For now I am keeping the local changes in the module for my app.

Regards,

**Comment by sarathkcm** [comment]
Well, thanks for that snippet.. :) . Its clean...
