### ISSUE TITLE
[hash] end checksum added to array_checksum before start checksum

### ISSUE THREAD

**Issue by romaincointepas** [vankasteelj/opensubtitles-api#13]
https://github.com/vankasteelj/opensubtitles-api/blob/master/lib/hash.js#L88-L100

Both `fs.read` are started asynchronously, and sometimes it adds the checksum for the end of the file to `array_checksum` before the checksum for the beginning of the file.

**Comment by vankasteelj** [comment]
Hello, thanks, it does seem possible, although I think I never encountered the issue. Can you fix it?
Maybe fs.readSync()
