### ISSUE TITLE
Question: Season and episode params for movies?

### ISSUE THREAD

**Issue by amilajack** [vankasteelj/opensubtitles-api#14]
Is it possible to specify if the query is a movie so that the episode and season params can be ignored?

**Comment by amilajack** [comment]
Also can the season and episode be given as a number instead of a string?

**Comment by vankasteelj** [comment]
>

**Comment by vankasteelj** [comment]
> Is it possible to specify if the query is a movie so that the episode and season params can be ignored?

Yes. Quoting the documentation: No parameter is mandatory, but at least one is required.

> Also can the season and episode be given as a number instead of a string?

Yes, absolutely
