### ISSUE TITLE
Recommendation about usage

### ISSUE THREAD

**Issue by amilajack** [vankasteelj/opensubtitles-api#16]
@vankasteelj From From your experience, what have you found to be the best way of finding accurate subtitles for a movie? A lot of the time when querying subtitles, the returned subtitles are for the correct movie but are 'off sync with the movie'. Do you know how to correct this? Which params have you found to be most important when finding the correct movie (infohash, imdb, etc)?

**Comment by vankasteelj** [comment]
Using every information you have is important to populate the subtitles, but infohash is the only one "matching perfectly". There is, imo, no way of having perfect match for every try.

**Comment by amilajack** [comment]
I see. Thanks!
