### ISSUE TITLE
What are the limitations of this API?

### ISSUE THREAD

**Issue by kaue** [vankasteelj/opensubtitles-api#18]
There is a request limitation per user or ip?

Thanks.

**Comment by vankasteelj** [comment]
afaik it is limited to 200 downloads per 24 hours (per user or per ip), but I'm not aware of any request restriction.

**Comment by kaue** [comment]
Thanks! a User is neded for download?

**Comment by vankasteelj** [comment]
Everything is already written in the documentation (readme.md and follow the external links)

**Comment by kaue** [comment]
Thanks.
