### ISSUE TITLE
Cannot get authorized

### ISSUE THREAD

**Issue by sunabozu** [vankasteelj/opensubtitles-api#3]
Hi.

I'm trying to login with my credentials, but always get `401 Unauthorized`. I use `OSTestUserAgent` UserAgent, as recommended in the [documentation](http://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst). I tried both plain text and md5 encrypted password.

**Comment by vankasteelj** [comment]
Hi,

You must be doing something wrong, probably with your credentials. Here's me logging in with my creds, without any issue:

![sh_2016-02-09_14-45-08](https://cloud.githubusercontent.com/assets/12599850/12917826/002b209e-cf3c-11e5-9aca-5ccf71d89c02.png)

Check that your username/password are correct, and also maybe try a "anonymous" login, by not providing any username/pw at all, just to test.

**Comment by sunabozu** [comment]
I just checked once again, and now it works. I didn't change anything since this morning, so it were some server issues, I guess. I think the problem doesn't exist anymore, so we can close this issue. Sorry to disturb you.

**Comment by vankasteelj** [comment]
no worries
