### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by mabdo250** [vankasteelj/opensubtitles-api#37]
npm install opensubtitles-api

npm ERR! code ETARGET
npm ERR! notarget No matching version found for opensubtitles-api@^1.3.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by vankasteelj** [comment]
You'll have to check with NPM. I only provide the current sources starting at 2.0.0

![mintty_2018-06-02_21-11-06](https://user-images.githubusercontent.com/12599850/40879982-a23ca6bc-66a9-11e8-9bd4-11abed7b492e.png)
