### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by jerlam06** [vankasteelj/opensubtitles-api#40]
This simply does not work.

**Comment by vankasteelj** [comment]
this comment simply doesn't work for me neither (btw, I use this everyday and it does work).

**Comment by jerlam06** [comment]
I am sorry, it seems my entire message is missing, I do not know what happened. Here is my full message:

Here is my code:
````
OpenSubtitles.search({
    sublanguageid: 'all',       // Can be an array.join, 'all', or be omitted.
    filename: 'skyscraper',        // The video file name. Better if extension
                                //   is included.

    extensions: ['srt', 'vtt'], // Accepted extensions, defaults to 'srt'.
    limit: '3',                 // Can be 'best', 'all' or an
}).then(subtitles => {
    // an array of objects, no duplicates (ordered by
    // matching + uploader, with total downloads as fallback)
    var keys = Object.keys(subtitles);
    for (var i = 0, len = keys.length; i < len; i++) {
        console.log(subtitles[keys[i]]);
    }
    console.log(subtitles)
});
````

This simply does not work.

EDIT: is there a way to search only with the movie name? This is maybe the reason why it does not work for me.

**Comment by vankasteelj** [comment]
Have you tried using "query" instead of "filename" as your code snippet seems to be using a really uncommon filename and I doubt someone already uploaded a subtitle using a videofile named "skyscraper" only. 

I get many results that way. 

You might want to read the Opensubtitles API docs on their website for reference

**Comment by jerlam06** [comment]
Thanks for your message. I tried with a query:
```
`    OpenSubtitles.search({
        sublanguageid: 'fre',       // Can be an array.join, 'all', or be omitted.
        query: 'Mission+Impossible.Fallout.2018.720p.KORSUB.HDRip.x264.AAC2.0-STUTTERSHIT',        // The video file name. Better if extension
                                    //   is included.

        extensions: ['srt', 'vtt'], // Accepted extensions, defaults to 'srt'.
        limit: '3',                 // Can be 'best', 'all' or an
                                    // arbitrary nb. Defaults to 'best'
        // imdbid: '528809',           // 'tt528809' is fine too.
        // fps: '23.96',               // Number of frames per sec in the video.
        // query: 'Charlie Chaplin',   // Text-based query, this is not recommended.
        gzip: true                  // returns url to gzipped subtitles, defaults to false
    }).then(subtitles => {
        // an array of objects, no duplicates (ordered by
        // matching + uploader, with total downloads as fallback)
    
        console.log(subtitles)
    });`
```
But it returns an empty object.

EDIT: My bad, when I change the language to 'en' it works, but I get all the languages, such as Romanian, Hebrew, Croatian; Bengali...etc even though I only specify 'en', is that normal?

**Comment by vankasteelj** [comment]
Ok, so: 

1) it returns an empty object with 'fre' because there is no french subtitle available
2) you need to change your language to 'eng', it's a 3-letter search. See opensubtitles documentation for more information on 3-letter-code for language

Everything is working as expected, thus I'm closing this
