### ISSUE TITLE
[Feature request ] VTT

### ISSUE THREAD

**Issue by team-pct** [vankasteelj/opensubtitles-api#41]
As Opensubtitles included a vtt converter on the fly we would love to see it included on opensubtitles.api as a prototype maybe ? fetchvtt ? 

Thank you !

**Comment by vankasteelj** [comment]
That feature seems undocumented. Could you provide some intel on that converter?

**Comment by team-pct** [comment]
I have looked into their forum and i found when we add subformat-vtt to the url of the opensubtitles-api it should use their converter BUT ... as Opensubs seem having hard time to keep the api up

**Comment by vankasteelj** [comment]
The issue is always the same: Opensubtitles is quite unstable, and externalizing their tools is hard in node-modules as they use mostly Python, which is great for correctly decoding the charsets, but isn't really JS-friendly

**Comment by team-pct** [comment]
That is why we are using opensubtitles-api , maybe give it an option as its return a list of srt on different lang maybe giving an option to opensub-api users to use the array full of vtt url ?

**Comment by vankasteelj** [comment]
https://dl.opensubtitles.org/en/download/src-api/vrf-19dd0c5a/sid-Kz9akbTrUYkNXXME,XK2Cr4TgF1/subformat-vtt/filead/1956099901
