### ISSUE TITLE
Why results on the API and on the OpenSubtitles portal not always match?

### ISSUE THREAD

**Issue by danielortiz** [vankasteelj/opensubtitles-api#43]
I'm searching the following query

```
  sublanguageid: 'pob,eng',
  filesize: 3316469975,
```
which is giving me no results

if I do the same search on the portal, I get some

![image](https://user-images.githubusercontent.com/40473589/51272464-4dff6600-19b1-11e9-8c91-09799a5ee0f8.png)

**Comment by vankasteelj** [comment]
If you use os.search(), you're using my custom algorithm. Use os.api.SearchSubtitles() if you want raw data from opensubtitles' servers

taken from readme: 
![firefox_2019-01-16_21-00-24](https://user-images.githubusercontent.com/12599850/51275296-d0981d80-19d1-11e9-82a9-60d440816a69.png)

**Comment by danielortiz** [comment]
sweet, thanks :)
