### ISSUE TITLE
Supported in browsers?

### ISSUE THREAD

**Issue by eioo** [vankasteelj/opensubtitles-api#44]
Is there any browser support or this purely for server-side node.js?

**Comment by vankasteelj** [comment]
It uses requirejs so I doubt it.

**Comment by eioo** [comment]
I think you could use bundler like Webpack or Parcel for it. I did some research and it seems XML-RPC 
package spoofs the User-Agent header, and current modern browsers (FF, Chrome) disallow that completely so it wouldn't work anyways.

**Comment by ghost** [comment]
i tried using `browserify main.js -o bundle.js` and it worked, but the bundle.js file size is 1mb+
