### ISSUE TITLE
How does GetAvailableTranslations work?

### ISSUE THREAD

**Issue by jerlam06** [vankasteelj/opensubtitles-api#45]
I am trying to get all the available subtitle languages for a given movie, will GetAvailableTranslations help me? 

I really don't understand this function, it takes 2 args: token, program. What do they mean by program?

Thanks

**Comment by vankasteelj** [comment]
Hi, you should ask this to opensubtitle, here I only wrote a wrapper. https://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC#GetAvailableTranslations
