### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by garyking** [vankasteelj/opensubtitles-api#51]
Please add TypeScript type definitions to this when you can. 

I know this has been suggested before. But it seems like they gave the impression that this project needs to be converted to TS. Instead, just a type declaration file is needed to be created.

A simple example, is if the project has a single function like:

```js
function sum(a, b) {
  return a + b;
}
```

Then the type declaration file is:

```ts
export function sum(a: number, b: number): number;
```

Which simply defines the types needed for the inputs and outputs. This is in turn, used by IDEs like VS Code to show to the user, in type hints. 

Please at least leave this issue open, so that this can be built over time, or if you have time.

**Comment by garyking** [comment]
I can submit an incomplete type def, if you're willing to merge it. To get things started. It's what I'm using now. I only use the `search` method, so that's why I only have created a type def for myself, with only that method.

**Comment by vankasteelj** [comment]
So it's more like documentation stuff? As long as it doesn't change the core code as it is now, and I don't have to maintain it, feel free to PR.

**Comment by garyking** [comment]
Yep, it's pretty much like documentation. It's used by TypeScript, but JavaScript can also use it (through IDEs like VS Code).

It doesn't require any changes to existing code at all. A `types` key must be added to `package.json`. I'll hopefully submit a PR soon.

**Comment by garyking** [comment]
On second thought, an incomplete type definition file probably isn't a good idea. But I'll post what I've got so far, here, for anyone in the future who wants to take this up. And I'll close this issue.

```ts
class OpenSubtitles {
  constructor(userAgent: string);

  search({
    sublanguageid,
    path,
    limit,
  }: {
    sublanguageid: string;
    path: string;
    limit: string;
  }): Promise<Record<string, OpenSubtitles.SearchResult[]>>;
}

namespace OpenSubtitles {
  interface SearchResult {
    url: string;
    langcode: string;
    downloads: number;
    lang: string;
    encoding: string;
    id: string;
    filename: string;
    date: string;
    score: number;
    fps: number;
    format: string;
    utf8: string;
    vtt: string;
  }
}

export = OpenSubtitles;
```
