### ISSUE TITLE
Issue: vtt subtitle download not working

### ISSUE THREAD

**Issue by Azmodeos** [vankasteelj/opensubtitles-api#55]
Download link for vtt doesn't work, i have extensions: ['srt', 'vtt'] passed on and as a result i get url, utf8 & vtt.

Both download links for url and utf8 work and download srt files but vtt doesn't work, am i doing something wrong or?

**Comment by darklight147** [comment]
Nice

**Comment by vankasteelj** [comment]
It's working fine here:

```js
OpenSubtitles.search({
    sublanguageid: 'eng', // Can be an array.join, 'all', or be omitted.
    extensions: ['srt', 'vtt'], // Accepted extensions, defaults to 'srt'.
    imdbid: "tt0322259", // 'tt528809' is fine too.
    limit: 3
  }).then(console.log)
```

Gives me this link: `https://dl.opensubtitles.org/en/download/subformat-vtt/src-api/vrf-19dd0c5f/sid-TgyrJaNV-Yrf4G2hpp9yhEgCfxc/filead/1952859375`

Which is a link to a .vtt file, I can download it. So I don't see where your problem is? What's a non-working url you get from the API?

**Comment by Azmodeos** [comment]
i did this

``
OpenSubtitles.search({
    sublanguageid: 'eng',
    extensions: ['srt', 'vtt'],
    imdbid: "tt4566758",
    limit: 3
  }).then(console.log)
``

and i got this vtt link `https://dl.opensubtitles.org/en/download/subformat-vtt/src-api/vrf-19d20c58/sid-plujGJoHyMFfZxVehOrceOq-Ova/filead/1956905363`

it's not working but yours for some reason is working.
Tried again with your imdbid that you tested and it worked so does it matter on the movie perhaps? like does it not work for all movies

**Comment by vankasteelj** [comment]
You should ask that question to opensubtitles, the link is sent by their servers. As far as opensubtitle-api, a wrapper to help discuss with opensubtitles directly, it seems to give you a correct url (the fact that this url isn't working isnt the wrappers fault), hence I'm closing this.
