### ISSUE TITLE
OpenSubtitles.search() not returning anything.

### ISSUE THREAD

**Issue by jbgaard** [vankasteelj/opensubtitles-api#56]
I am trying to use the OpenSubtitles API NPM package in my electron App.

OpenSubtitles API
https://github.com/vankasteelj/opensubtitles-api

However there is problem.

When i run this command to search for subtitles for a specified movie using its IMDB id and then sorting the results for a specific language: 

```javascript
	const OpenSubtitlesApi = require('opensubtitles-api');
	const OpenSubtitles = new OpenSubtitlesApi({
    	useragent:'UserAgent',
    	username: 'username',
    	password: 'password1',
    	ssl: true
	});

    OpenSubtitles.search({
    	sublanguageid: 'eng',
    	extensions: ['srt', 'vtt'],
    	imdbid: "tt0322259",
    	limit: 3
    }).then(res => {
    	console.log(res);
    }).catch(err => {
		console.log(err);
	);
```

It should respond with an object / array like this:

```javascript

{
	0:
		date: "2011-05-15 13:19:33"
		downloads: 54215
		encoding: "CP850"
		filename: "The.Fast.And.The.Furious.II.2003.BluRay.720p.x264.DTS-WiKi.eng.srt"
		format: "srt"
		fps: 23.976
		id: "1952859375"
		lang: "English"
		langcode: "en"
		score: 0.5
		url: "https://dl.opensubtitles.org/en/download/src-api/vrf-19dd0c5f/sid-3DRrLRTBf9EAZEfRVAnmx,rlso0/filead/1952859375"
		utf8: "https://dl.opensubtitles.org/en/download/subencoding-utf8/src-api/vrf-19dd0c5f/sid-3DRrLRTBf9EAZEfRVAnmx,rlso0/filead/1952859375"
		vtt: "https://dl.opensubtitles.org/en/download/subformat-vtt/src-api/vrf-19dd0c5f/sid-3DRrLRTBf9EAZEfRVAnmx,rlso0/filead/1952859375"
}
```
But instead i get nothing. It doesnt error, otherwise the `catch()` would have caught it.

I have tried running the entire thing inside a `SetInterval(() => {}, 100);` where it will eventually return a response and then shortly error because i am spamming the openSubtitles servers.

The function is placed inside a `$(document).ready();` which should wait for the document to be loaded, before proceeding - and it is also placed inside a `setTimeout(() => {}, 5000);` function to make sure the document is finished loading.

I have a suspiscion it is because it exists the `.then()` before it finishes and therefore it doesnt console.log(); the response it receieves? How do i test this further, or how do i stop it from exiting the then() if that is why this happens. 

It might also be because it is thrown into a queue and not ended correctly, because when i paste the exact same function to call `OpenSubtitles.Search()` and paste it into the DevTools console, the response is the original call in the document.

Really hoping someone can help me out here :).

**Comment by jbgaard** [comment]
If i begin another promise it then returns the response from the first one.
Example: 
If i run the .login();
`OpenSubtitles.login().then(res => {
  	console.log(res.token)
	console.log("Logget ind!")
	tokenSub = res.token;
}).catch((err) => {
  console.log("Der er sket en fejl med at logge ind " + err)
})`

I get no response. But if i run another promise based function. If i run the OpenSubtitles.search(); function i get a response from the first function???

If i run this small example:

`console.log("Attempt login.")

OpenSubtitles.login().then(res => {
  	console.log(res.token)
	console.log("Login Success!")
	tokenSub = res.token;
}).catch((err) => {
	console.log(err)
})

console.log("Searching for subtitles")
OpenSubtitles.search({
	sublanguageid: 'eng',       // Can be an array.join, 'all', or be omitted.
	extensions: ['srt', 'vtt'], // Accepted extensions, defaults to 'srt'.
	imdbid: "tt0322259",           // 'tt528809' is fine too.
	limit: 3
}).then(function(resulthaha) {
	console.log(resulthaha);
	console.log("Received subtitles");

}).catch(err => {
	console.log(err);
});`

This is the message i get in the console.

```
Attempt login.
openSubTest.js:18 Searching for subtitles
RkC0RUMXd6AF0Qxcyw-EUeh,eM0
openSubTest.js:12 Login Success!
openSubTest.js:41 Promise {<pending>}
openSubTest.js:25 {en: Array(3)}
openSubTest.js:26 Received subtitles
```

This is a clean document it has nothing more than this.

Pictures for proof:
Source
![image](https://user-images.githubusercontent.com/46847021/93907203-574fe280-fcfd-11ea-9155-30fbae926648.png)
Console.
![image](https://user-images.githubusercontent.com/46847021/93907441-a0079b80-fcfd-11ea-9c57-a48ea10a04a8.png)

Help and suggestions are very much appreciated! 👍

**Comment by vankasteelj** [comment]
For your first post, here's what I've got when I try your code, so it does error correctly (you forgot to close a bracket btw): 
![Frak_sU8OjFH0Io](https://user-images.githubusercontent.com/12599850/94289494-13591980-ff59-11ea-8da8-01a6344298e0.png)

**Comment by vankasteelj** [comment]
I also used your code but removed the username/password, which is required to log in, because it isnt necessary to do a search, and I've got a response
![Frak_MuSZX1Vwg3](https://user-images.githubusercontent.com/12599850/94289943-c9bcfe80-ff59-11ea-90bf-e7a56d27754a.png)

**Comment by jbgaard** [comment]
If i paste the code into the console, it runs fine. If i do it in a document, it doesnt work properly.

I have this plain document to test with.

```javascript
const OS = require('opensubtitles-api');
const OpenSubtitles = new OS({
    useragent: 'UserAgent',
    ssl: true
});

console.log("Attempt login.")
OpenSubtitles.search({
	sublanguageid: 'eng',
	extensions: ['srt', 'vtt'],
	imdbid: "tt0322259",
	limit: 3
}).then(function(res) {
	console.log(res);
}).catch(err => {
	console.log(err);
});
```

Nothing is returned. But if add a second login() or search() i get a reponse from the first attempt, but not the second.

Pictures:
Source Pic
![billede](https://user-images.githubusercontent.com/46847021/94290540-9f1f7580-ff5a-11ea-9189-20d789dd9e3f.png)
Console Pic
![billede](https://user-images.githubusercontent.com/46847021/94290547-a21a6600-ff5a-11ea-9367-26fb1e81f526.png)

**Comment by vankasteelj** [comment]
As for you second post, either you don't get how promises work, or I'm missing something. Thenable promises are triggered when the response is available so if you do: 

```
Promise( wait for 10 seconds).then( log "I waited 10 sec"); 
Promise( wait for 1 second).then( log "I waited 1 sec"); 
```

You'll get this on the console (let's say it's 9am for the example):

```
09:00:01 - I waited 1 sec
09:00:10 - I waited 10 sec
```

-------------

If you want to wait 1 second AFTER waiting 10 seconds, you need to : 

```
Promise( wait for 10 seconds).then( log "I waited 10 sec" ).then( wait for 1 seconde).then( log "I waited 1 sec")
```

-------------

So what I'm saying is, try this instead: 

```js
console.log("Attempt login.")

OpenSubtitles.login().then(res => {
  console.log(res.token)
  console.log("Login Success!")
  tokenSub = res.token;
  return OpenSubtitles.search({
    sublanguageid: 'eng', // Can be an array.join, 'all', or be omitted.
    extensions: ['srt', 'vtt'], // Accepted extensions, defaults to 'srt'.
    imdbid: "tt0322259", // 'tt528809' is fine too.
    limit: 3
  })
}).then(resulthaha => {
  console.log(resulthaha);
  console.log("Received subtitles");
}).catch((err) => {
  console.log(err)
})
```

**Comment by jbgaard** [comment]
I've tried something similar earlier in the error/confusion/debugging process, when i copy and insert the example you provided above. It gets stuck on Attempt login and stays there.

And i know the way it was setup in the example code was _"stupid"_, but after trial and error this was the only way to get some sort of response. May also be because i have confused myself.

Pic Console:
![billede](https://user-images.githubusercontent.com/46847021/94291325-c4f94a00-ff5b-11ea-9e79-7e52af56d94b.png)

**Comment by vankasteelj** [comment]
Well, it's working fine here: 
![Frak_w05shdsMUl](https://user-images.githubusercontent.com/12599850/94291510-07bb2200-ff5c-11ea-8066-cada5e604dae.png)

**Comment by jbgaard** [comment]
When i paste it into the console, it returns everything fine. But when i run it inside my openSubTest.js and load that, it does not respond. 🤔

![billede](https://user-images.githubusercontent.com/46847021/94291810-5ec0f700-ff5c-11ea-9aab-b7da6435119b.png)

**Comment by vankasteelj** [comment]
Well, it's working fine on node, even as a file. The problem is somewhere in your electron app, because I use it in multiple applications (and just made a new test folder for that file), and it works: 

![Brackets_Jhp6zqZEcY](https://user-images.githubusercontent.com/12599850/94292445-43a2b700-ff5d-11ea-8f57-dfabe07066c3.png)

**Comment by jbgaard** [comment]
It seems to be my pc which is acting up.

I have tried testing it directly in node, and it works fine 👍 - also got ahold of another pc to test on, and here it also works fine (Both in electron and nodejs).

It seems i have wasted your time, and i am very sorry!

**Comment by vankasteelj** [comment]
Try cleaning your directories, re-download node/electron. There is no need to apologise, hope I could help another tinkerer
