### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by devmatant** [vankasteelj/opensubtitles-api#61]
in code updated files for support italian language

PATH\OpenSUbtitles Uploader\app\js\utils\localization.js = add 'it' option

PATH\OpenSUbtitles Uploader\app\localization\it.json =

	"Upload": "Carica",
	"Log in": "Accedi",
	"Log out": "Disconnetti",
	"Username": "Utente",
	"Password": "Password",
	"Video file": "File Video",
	"Subtitle file": "Sottotitolo",
	"Drop a video file or select one": "Trascina o seleziona un Video",
	"Drop a subtitle file or select one": "Trascina o seleziona un Sottotitolo",
	"Metadata": "Metadati",
	"browse": "naviga",
	"Save between sessions": "Mantieni",
	"Search on IMDB directly": "Cerca su IMDB",
	"Auto-detect the language": "Lingua Automatica",
	"Reset": "Resetta",
	"File name": "Nome File",
	"OSDb Hash": "OSDb Hash",
	"MD5 Hash": "MD5 Hash",
	"Size": "Dimensioni",
	"bytes": "bytes",
	"High definition": "HD",
	"Movie AKA": "Vdeo AKA",
	"Release name": "Nome Release",
	"FPS": "FPS",
	"Total time": "Durata",
	"Number of frames": "Numero Frame",
	"Language": "Lingua",
	"None": "Nessuno",
	"Comment": "Commento",
	"Hearing impaired": "Non Udenti",
	"Auto-translated": "Auto-tradotto",
	"Translator": "Traduttore",
	"developed by": "sviluppato da",
	"Enter a title": "Inserisci un Titolo",
	"Search": "Cerca",
	"OK": "OK",
	"EDIT": "MODIFICA",
	"UPLOAD": "CARICA",
	"RETRY": "RIPROVA",
	"OPEN IN BROWSER": "APRI NEL BROWSER",
	"YES": "SI",
	"NO": "NO",
	"Language testing unconclusive, automatic detection failed": "Impossibile determinare lingua",
	"Video cannot be imported because OpenSubtitles could not be reached. Is it online?": "Il Video non può essere importato, OpenSubtitles è online?",
	"Unknown OpenSubtitles related error, please retry later or report the issue": "Errore sconosciuto di OpenSubtitles, riprova o segnala il problema",
	"IMDB id mancante per il file. Raccomndimamo di inserirlo, per categorizzarlo meglio e rendere facile il download.": "IMDB id mancante per il file. Raccomndimamo di inserirlo, per categorizzarlo meglio e rendere facile il download.",
	"Wrong username or password": "Username o Password Errati",
	"Not found": "Non Trovato",
	"Wrong IMDB id": "IMDB id errato",
	"New version available, download %s now!": "Aggiornamento disponibile, download %s in corso!",
	"Dropped file is not supported": "Il file inserito non è supportato",
	"Cut": "Taglia",
	"Copy": "Copia",
	"Paste": "Incolla",
	"Subtitle was already present in the database": "Sottotitolo già esistente",
	"The hash has been added!": "Hash inserito!",
	"The hash too...": "L'hash è lo stesso...",
	"The file name has been added!": "Nome file inserito!",
	"The file name too...": "Il nome file è lo stesso...",
	"Subtitle was successfully uploaded!": "Sottotitolo caricato correttamente!",
	"OpenSubtitles is temporarily unavailable, please retry in a little while": "OpenSubtitles è irragiungibile, riprova tra poco",
	"OpenSubtitles is under maintenance, please retry in a few hours": "OpenSubtitles è in manutenzione, riprova tra qualche ora (CEST 08:30)",
	"Something went wrong :(": "Qualcosa è andato storto :(",
	"IMDB id": "IMDB id",
	"Switch theme": "Cambia Tema",
	"Formato sottotitolo non valido, controllalo prima di caricarlo su OpenSubtitles (Rimuovi gli url, spam e effetti ASS non consentiti)": "Formato sottotitolo non valido, controllalo prima di caricarlo su OpenSubtitles (Rimuovi gli url, spam e effetti ASS non consentiti)",
	"Il sottotitolo contiene descrizioni delle scene, interiezioni e dialoghi specifici per i non udenti": "Il sottotitolo contiene descrizioni delle scene, interiezioni e dialoghi specifici per i non udenti",
	"The subtitles were translated automatically by a machine": "I sottotitoli sono stati tradotti automaticamente",
	"Foreign parts only": "Solo Forzati",
	"The subtitles only translate non-native parts of the script, for example elvish and orkish in the Lord of the Rings": "The subtitles only translate non-native parts of the script, for example elvish and orkish in the Lord of the Rings",
	"Replace the currently loaded file with the detected one: %s": "Sostituisci file precedente con quello attuale: %s",
	"Settings": "Impostazioni",
	"Theme": "Temi",
	"Check for updates": "Controlla aggiornamenti",
	"help translating": "Aiuta a tradurre",
	"Import file(s)": "Importa file",
	"Clear file(s)": "Chiudi file",
	"Close popup(s)": "Chiudi popup",
	"Developer tools": "Strumenti Sviluppatore",
	"Next field": "Scheda successiva",
	"Previous field": "Scheda precendente",
	"Report an issue": "Segnala un proglena (eng)",
    "Use HTTPS": "Usa HTTPS",
    "This IMDB id could not be checked, be careful with your upload": "This IMDB id could not be checked, be careful with your upload"

**Comment by vankasteelj** [comment]
See https://github.com/vankasteelj/opensubtitles-uploader/issues/100
