### ISSUE TITLE
Issue in Identify.js

### ISSUE THREAD

**Issue by sarathkcm** [vankasteelj/opensubtitles-api#7]
Hi,

Awesome work.... :+1: 

I noticed an issue in identify.js, if a movie/series does not have a plot/synopsis, the following line will throw exception, since plot is undefined. Could you please fix this minor issue?

`data.metadata.synopsys = response.data.plot.match(/add a plot/i) !== null ? undefined : response.data.plot;` 

PS: Also, just saying, 'synopsis' is the right spelling. :)

**Comment by sarathkcm** [comment]
A small change only, this should do-

`data.metadata.synopsys = response.data.plot && response.data.plot.match(/add a plot/i) !== null ? undefined : response.data.plot;`

**Comment by vankasteelj** [comment]
sadly i can't change to synopsis without bumping a major version, it's incompatible change. I'll wait a little before bumping. can you open a new issue for this mispelling? thx

**Comment by sarathkcm** [comment]
Hi, Thanks for fixing the issue.
I see that you have already opened another issue for the typo.
